# https://taskfile.dev
version: '3'
tasks:
  setup-hello:
    cmds:
    - |
      mkdir hello
      cd hello
      tsc --init

  install-ts:
    desc: install type-script
    cmds:
    - npm i -g typescript
    - tsc --version
